value=0;
start=0;
stop=100000;
animation_frame =0;
length=400;
height=30
bw=5//borderWidth
shown=true
animation=instance_create_depth(x+(length/2),y-200,depth,Animation)
animation.sprite_index = sShuffleAnimation;